name: ebook_reader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  dio: ^5.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  rename_app: ^1.3.1
  vocsy_epub_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
